### ISSUE TITLE
clj portion fails to build under 1.7.0

### ISSUE THREAD

**Issue by canweriotnow** [lbradstreet/instaparse-cljs#8]
It's this error, fixed in upstream 1.4.0: https://github.com/Engelberg/instaparse/issues/90

**Comment by lbradstreet** [comment]
Thanks for the report. I've been meaning to bring things into sync with 1.4.0 but I might only be able to get around to it in a week or two. 

Cheers

**Comment by canweriotnow** [comment]
@lbradstreet no worries, I'm pretty new to your cljs port, how is test coverage? I might have some time to hack on it if I can rely on the tests to confirm it's correct?

**Comment by lbradstreet** [comment]
Test coverage is pretty good. All the CLJ tests worked for CLJS.

I just merged from upstream and all the tests still work except core-test.cljx/parsing-tutorial, because of the lack of StringBuilder in cljs and because the test hasn't been ported yet.

You can run the cljs tests by installing nodejs and running lein cleantestcljs. Feel free to jump in - I won't have a chance to push it much further for the next few days.

Note, any instaparse changes between v1.3.5-v1.4.0 haven't been ported to the clojurescript version yet, so there may be some missing features/bug fixes in master.

**Comment by canweriotnow** [comment]
Cheers, I'll play with it when I get a sec!

**Comment by lbradstreet** [comment]
I disabled that test on cljs, as there's no need to be able to accept StringBuilders as input on cljs. All the test now pass. Enjoy.

**Comment by lbradstreet** [comment]
Looks like there's one more failing test. I think that one will require porting a fix from the latest CLJ code.

**Comment by canweriotnow** [comment]
:+1:
